repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, --unsafe-fixes]
      # Run the formatter.
      - id: ruff-format