---
apiVersion: batch/v1
kind: Job
metadata:
  name: trades-historical
  namespace: ingestion-pipeline
  labels:
    app: trades-historical
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: trades-historical
    spec:
      restartPolicy: Never
      containers:
      - name: trades-historical
        image: ghcr.io/brunoclbr/trades:0.1.5-beta.1754045020@sha256:8616bb8c930fe681581dbd2e2a9715f7828555e42e4a5841dd88dfc2e3a45e33
        imagePullPolicy: Always # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: KAFKA_BROKER_ADDRESS
        - name: KAFKA_TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TRADES_TOPIC
        - name: LIVE_OR_HISTORICAL
          value: "historical"
        - name: LAST_N_DAYS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: LAST_N_DAYS  
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: candles-historical
  namespace: ingestion-pipeline
  labels:
    app: candles-historical
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: candles-historical
    spec:
      restartPolicy: Never
      containers:
      - name: candles-historical
        image: ghcr.io/brunoclbr/candles:0.1.5-beta.1753442993@sha256:a226503bcacf467c958d6f4d85693a26a5ae0e50f490ec5a003395cfd7d24061
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: KAFKA_BROKER_ADDRESS
        - name: KAFKA_INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TRADES_TOPIC
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLES_TOPIC
        - name: KAFKA_CONSUMER_GROUP
          value: "candles_consumer_group"
        - name: CANDLE_SECONDS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLE_SECONDS
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: technical-indicators-historical
  namespace: ingestion-pipeline
  labels:
    app: technical-indicators-historical
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: technical-indicators-historical
    spec:
      restartPolicy: Never
      containers:
      - name: technical-indicators
        image: ghcr.io/brunoclbr/technical-indicators:0.1.5-beta.1753443588@sha256:0057baad92237c9f170261e2b49050bb3ed147f6003b3c86df24e535b06aaf84
        imagePullPolicy: Always
        env:
        #
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: KAFKA_BROKER_ADDRESS
        #
        - name: KAFKA_INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLES_TOPIC
        #
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: TECHNICAL_INDICATORS_TOPIC
        #
        - name: KAFKA_CONSUMER_GROUP
          value: "technical_indicators_group"
        #
        - name: CANDLE_SECONDS
          valueFrom:
            configMapKeyRef:
              name: backfill-technical-indicators
              key: CANDLE_SECONDS
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
