apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-indicators
  namespace: ingestion-pipeline
  labels:
    app: technical-indicators
spec:
  replicas: 2
  selector:
    matchLabels:
      app: technical-indicators
  template:
    metadata:
      labels:
        app: technical-indicators
    spec:
      containers:
      - name: technical-indicators
        image: ghcr.io/brunoclbr/technical-indicators:0.1.5-beta.1753443588@sha256:0057baad92237c9f170261e2b49050bb3ed147f6003b3c86df24e535b06aaf84
        imagePullPolicy: Always # Make sure we use the latest docker images fronm the github container registry, disregarding the caches images that kubernetes might have.
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "candles"
        - name: KAFKA_OUTPUT_TOPIC
          value: "technical_indicators"
        - name: KAFKA_CONSUMER_GROUP
          value: "technical_indicators_group"
        - name: CANDLE_SECONDS
          value: "60"