---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  namespace: ingestion-pipeline
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
      - name: trades
        image: ghcr.io/brunoclbr/trades:0.1.5-beta.1753442905@sha256:9dc11b3942c205c3d9719dcab8e9c348ca9396537aa91b5417f5b51dc11faac9
        imagePullPolicy: Always
        #
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_TOPIC_NAME
          value: "trades"
        - name: LIVE_OR_HISTORICAL
          value: "live"
        #
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi